name: TravelMate
description: "A new Flutter project."
 
publish_to: 'none'  
 
version: 1.0.0+1

environment:
  sdk: ^3.6.1
 
dependencies:
  curved_navigation_bar: ^1.0.3
 
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.0
  firebase_auth: ^4.18.0
  provider: ^6.1.2
  cloud_firestore: ^4.17.5
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.1
  carousel_slider: ^5.0.0
  flutter_animate: ^4.5.2
  animate_do: ^4.2.0
  firebase_dynamic_links: ^5.5.7
  
  


dev_dependencies:
  
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
 

flutter:
  uses-material-design: true

  assets:
    - assets/
  
flutter_icons:
  android: true
  image_path: "assets/llogo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/llogo.png"

